### ISSUE TITLE
RNRestart.Restart() reloads the notification or universal link the app was originally opened with

### ISSUE THREAD

**Issue by amacrobert-meq** [avishayil/react-native-restart#51] opened 2018-11-05 22:06 UTC
I think a great feature would be the ability to restart without reloading the initial URL or push notification if the app was originally opened with either of those.

I'm using RNRestart when a user logs out, as an easy way to clear redux and all user data.

However, if the app was originally opened via push notification, the system shows that push again after reload.

It's also the case that if the app was opened via Universal link (iOS) or Deep link (Android), that initial URL is also reloaded. This isn't so much an issue in my case because the login screen prevents the app from routing elsewhere, but it could be an issue for other people.

**Comment by bandhiwal** [comment] 2019-01-18 06:13
I am getting the same error and it is redirecting me to chat screen. How can I stop this? Any workaround?

**Comment by cjroth** [comment] 2019-05-08 01:13
It makes logical sense to me that this would happen, but I'm not able to reproduce this behavior with universal links on 0.59.5

**Comment by avishayil** [comment] 2019-06-04 05:28
This is something that probably needs some treatment, but we need a reproducable environment and community help, since it's not something I'm experiencing in my apps. I'm going to close this issue but if anyone searches this issue and finds a solution it would be great to fill a PR.

**Closed by avishayil** 2019-06-04 05:28 UTC
Labels: wontfix

**Comment by lorenjohnson** [comment] 2022-04-26 16:58
Realizing this is close with #wontfix I'm still watching 👀 for any solutions. There are obvious workarounds but none feel great and it'd be a real nice thing to have as a provision or option of the library to clear or otherwise ignore the `initialURL` at the native level on `RNRestart.Restart()` call. I have ideas, but unfortunately don't see the time to make this contribution myself at this time.
