### ISSUE TITLE
[ Android ] Random crashes

### ISSUE THREAD

**Issue by hydraZty** [avishayil/react-native-restart#12] opened 2017-06-07 08:58 UTC
When i use `RNRestart.Restart()` , it has random crash with no report. anybody else?

**Comment by alizahid** [comment] 2017-06-28 09:41
I don't think it's a random crash. It happens every time for me. Check the stack trace.

	06-28 14:38:31.446 9005-9047/com.example E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
		Process: com.example, PID: 9005
		java.lang.RuntimeException: An error occurred while executing doInBackground()
			at android.os.AsyncTask$3.done(AsyncTask.java:309)
			at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
			at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
			at java.util.concurrent.FutureTask.run(FutureTask.java:242)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
			at java.lang.Thread.run(Thread.java:818)
		Caused by: java.lang.IllegalStateException: closed
			at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:164)
			at com.facebook.react.devsupport.InspectorPackagerConnection$Connection.close(InspectorPackagerConnection.java:271)
			at com.facebook.react.devsupport.InspectorPackagerConnection.closeQuietly(InspectorPackagerConnection.java:48)
			at com.facebook.react.devsupport.DevServerHelper$4.doInBackground(DevServerHelper.java:221)
			at com.facebook.react.devsupport.DevServerHelper$4.doInBackground(DevServerHelper.java:217)
			at android.os.AsyncTask$2.call(AsyncTask.java:295)
			at java.util.concurrent.FutureTask.run(FutureTask.java:237)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
			at java.lang.Thread.run(Thread.java:818) 
	06-28 14:38:31.446 9005-9081/com.example I/Process: Sending signal. PID: 9005 SIG: 9

**Comment by mr-bat** [comment] 2017-10-09 17:29
It not only happens every time to me but also happens even in the release build.

**Comment by avishayil** [comment] 2017-10-16 21:44
Could you check if this still happens on the newest version?

**Comment by mr-bat** [comment] 2017-10-17 13:13
yes, it's the latest version

**Comment by avishayil** [comment] 2017-11-20 08:02
This should be fixed with https://github.com/avishayil/react-native-restart/commit/682c6d352959bb26735f415f9685274740ad351c

**Closed** 2017-11-20 08:07 UTC

**Comment by sapjax** [comment] 2017-11-21 03:05
Hi @avishayil   When react-native-restart use with `react-native-navigation`,   it will cause carsh on android when restart.

**Comment by avishayil** [comment] 2017-11-21 05:34
@sapjax could you share an example repo with the issue reproduced? Or supply stacktrace?

**Comment by ozsirma** [comment] 2017-12-07 08:51
@avishayil  I have same issue with @sapjax . How can I solve this problem ?

**Comment by sapjax** [comment] 2017-12-07 11:48
@ozsirma   Atlast， I use `Navigation.startTabBasedApp` to restart my app,  it's faster than real restart,  by the way, you need to rerun some process again (which should run before `startTabBasedApp`).

**Comment by ozsirma** [comment] 2017-12-07 12:11
Did you run for your project ? @sapjax What is the some process ?
Can you describe your process with sample codes ?

**Comment by sapjax** [comment] 2017-12-08 01:34
@ozsirma  Just the same thing run before `startTabBasedApp` when you start your app.
for example, when the user chooses a different language in our app,  we need to recall `startTabBasedApp` to restart the app,  before `restart` we need to init the `i18n` handle process, this is what I mean `some process`.

```js
function async restartApp() {
   await initI18n()
   startTabBasedApp({...})  
}
```

**Comment by ma-pe** [comment] 2018-06-06 14:00
This is still an issue for me. I use `react-router-navigation` if this may be related...

My android app just stops working, the native elements (scroll views, etc.) are still usable but no javascript is executed anymore. no restart either. `logcat` doesn't show any errors.

iOS works like a charm.

Any idea?

**Comment by ma-pe** [comment] 2018-06-06 15:16
I must correct myself: there seem certain situations where the described behaviour happens.

I couldn't combine the pattern yet, but this works in my situation:

```  
async restart() {
    // this is weird but necessary. dunno why.
    // if omitted, the app will become unresponsive.
    await delay(1000);

    RNRestart.Restart();
}
```

**Comment by mahmoudeldawy** [comment] 2020-09-22 12:56
hi use it in  "react-native": "0.63.2",
app crashes one time after installation 
`constructor(props) {
        super(props);
        if (I18nManager.isRTL != true) {
            I18nManager.forceRTL(true);
            RNRestart.Restart();
        }`
